SELECT SUBSTR(DF.TABLESPACE_NAME, 1, 20) "Tablespace Name",
       SUBSTR(DF.FILE_NAME, 1, 40) "File Name",
       ROUND(DF.BYTES / 1024 / 1024, 2) "Size (M)",
       ROUND(E.USED_BYTES / 1024 / 1024, 2) "Used (M)",
       ROUND(F.FREE_BYTES / 1024 / 1024, 2) "Free (M)",
       RPAD(' ' || RPAD('X', ROUND(E.USED_BYTES * 10 / DF.BYTES, 0), 'X'),
            11,
            '-') "% Used"
  FROM DBA_DATA_FILES DF,
       (SELECT FILE_ID, SUM(DECODE(BYTES, NULL, 0, BYTES)) USED_BYTES
          FROM DBA_EXTENTS
         GROUP BY FILE_ID) E,
       (SELECT MAX(BYTES) FREE_BYTES, FILE_ID
          FROM DBA_FREE_SPACE
         GROUP BY FILE_ID) F
 WHERE E.FILE_ID(+) = DF.FILE_ID AND DF.FILE_ID = F.FILE_ID(+)
 ORDER BY DF.TABLESPACE_NAME, DF.FILE_NAME;

----Tablespace usage-----

SELECT D.TABLESPACE_NAME,
       D.FILE_ID,
       D.FILE_NAME,
       D.BYTES ALLOCATED,
       NVL(F.BYTES, 0) FREE
  FROM (SELECT TABLESPACE_NAME, FILE_ID, FILE_NAME, SUM(BYTES) BYTES
          FROM DBA_DATA_FILES        
         GROUP BY TABLESPACE_NAME, FILE_ID, FILE_NAME) D,       
       (SELECT TABLESPACE_NAME, FILE_ID, SUM(BYTES) BYTES
          FROM DBA_FREE_SPACE        
         GROUP BY TABLESPACE_NAME, FILE_ID) F
 WHERE D.TABLESPACE_NAME NOT IN ('SYSTEM', 'SYSAUX')      
       AND D.TABLESPACE_NAME = F.TABLESPACE_NAME(+)      
       AND D.FILE_ID = F.FILE_ID(+)
 ORDER BY TABLESPACE_NAME, FILE_ID;

----Tablespace usage -----

SELECT SUBSTR(DF.NAME, 1, 40) FILE_NAME,
       DF.BYTES / 1024 / 1024 ALLOCATED_MB,
       ((DF.BYTES / 1024 / 1024) - NVL(SUM(DFS.BYTES) / 1024 / 1024, 0)) USED_MB,
       NVL(SUM(DFS.BYTES) / 1024 / 1024, 0) FREE_SPACE_MB
  FROM V$DATAFILE DF, DBA_FREE_SPACE DFS
 WHERE DF.FILE# = DFS.FILE_ID(+)
 GROUP BY DFS.FILE_ID, DF.NAME, DF.FILE#, DF.BYTES
 ORDER BY FILE_NAME;

-----
SELECT  SUM(bytes)/1024/1024 Mo , segment_name 
  FROM dba_extents
 WHERE owner = 'CDR'
GROUP BY segment_name 
ORDER BY 1 DESC;


SELECT * FROM CDR.GSM_CALL_ORIGINATED

alter table GSM_CALL_ORIGINATED add partition GSM_CALL_ORIGINATED_OLD values less than (1996);